mod NS-WHILE-PROOFS is

  pr STATE .
  pr WHILE-SYNTAX .
  pr A-SYNTAX .
  pr A-SEMANTICS .
  pr B-SYNTAX .
  pr B-SEMANTICS .

  sort Tree Config Result .
  subsort Config Tree < Result .

  op <_,_> : Stat State -> Config .
  op Bottom : -> State [ctor] .

  op skipns : Stat State State -> Tree .
  op assns : Stat State State -> Tree .
  op compns : Stat State Tree Tree State -> Tree .
  op ifttns : Stat State Tree State -> Tree .
  op ifffns : Stat State Tree State -> Tree .
  op whilettns : Stat State Tree Tree State -> Tree .
  op whileffns : Stat State State -> Tree .
  op repeatffns : Stat State Tree Tree State -> Tree .
  op repeatttns : Stat State Tree State -> Tree .
  op forttns : Stat State Tree Tree Tree State -> Tree .
  op forffns : Stat State State -> Tree .
  op abortns : Stat State State -> Tree .
  op compabortns : Stat State Tree State -> Tree .
  op whileabortns : Stat State Tree State -> Tree .
  op repeatabortns : Stat State Tree State -> Tree .
  op forabortns : Stat State Tree Tree State -> Tree .
  op assertttns : Stat State Tree State -> Tree .
  op assertffns : Stat State State -> Tree .
  op or1ns : Stat State Tree State -> Tree .
  op or2ns : Stat State Tree State -> Tree .
  op blockns : Stat State Tree Tree State -> Tree .
  op varns : Stat State Tree State -> Tree .
  op nonens : Stat State State -> Tree .

  op finalState : Tree -> State .

  vars M M' M'' M''' : State .
  vars Q : Qid .
  vars E E' : Exp .
  vars S S' : Stat .
  vars T T' T'' : Tree .
  vars C : Cond .
  var D : Decv .

  eq finalState(assns(S, M, M')) = M' .
  eq finalState(skipns(S, M, M')) = M' .
  eq finalState(compns(S, M, T, T', M')) = M' .
  eq finalState(ifttns(S, M, T, M')) = M' .
  eq finalState(ifffns(S, M, T, M')) = M' .
  eq finalState(whilettns(S, M, T, T', M')) = M' .
  eq finalState(whileffns(S, M, M')) = M' .
  eq finalState(repeatffns(S, M, T, T', M')) = M' .
  eq finalState(repeatttns(S, M, T, M')) = M' .
  eq finalState(forttns(S, M, T, T', T'', M')) = M' .
  eq finalState(forffns(S, M, M')) = M' .
  eq finalState(abortns(S, M, M')) = M' .
  eq finalState(compabortns(S, M, T, M')) = M' .
  eq finalState(whileabortns(S, M, T, M')) = M' .
  eq finalState(repeatabortns(S, M, T, M')) = M' .
  eq finalState(forabortns(S, M, T, T', M')) = M' .
  eq finalState(assertttns(S, M, T, M')) = M' .
  eq finalState(assertffns(S, M, M')) = M' .
  eq finalState(or1ns(S, M, T, M')) = M' .
  eq finalState(or2ns(S, M, T, M')) = M' .
  eq finalState(blockns(S, M, T, T', M')) = M' .
  eq finalState(varns(S, M, T, M')) = M' .
  eq finalState(nonens(S, M, M')) = M' .

  rl [assign] :
    < Q := E , M > => assns(Q := E, M, M [Q |-> A[E] M]) .

  rl [skip] :
    < skip , M > => skipns(skip, M, M) .

  crl [comp] :
    < (S ; S') , M > => compns((S ; S'), M, T, T', M'')
        if
            < S , M > => T
            /\ M' := finalState(T)
            /\ M' =/= Bottom
            /\ < S' , M' > => T'
            /\ M'' := finalState(T') .

  crl [comp-abort] :
     < (S ; S') , M > => compabortns((S ; S'), M, T, M')
        if
            < S , M > => T
            /\ M' := finalState(T)
            /\ M' = Bottom .

  crl [if-tt] :
    < if C then S else S' , M > =>
    ifttns((if C then S else S'), M, T, M')
        if
            B[C] M = true
            /\ < S , M > => T
            /\ M' := finalState(T) .

  crl [if-ff] :
    < if C then S else S' , M > =>
    ifffns((if C then S else S'), M, T, M')
        if
            B[C] M = false
            /\ < S' , M > => T
            /\ M' := finalState(T) .

  crl [while-tt] :
    < while C do S , M > =>
    whilettns((while C do S), M, T, T', M'')
        if
            B[C] M = true
            /\ < S , M > => T
            /\ M' := finalState(T)
            /\ M' =/= Bottom
            /\ < while C do S , M' > => T'
            /\ M'' := finalState(T') .

  crl [while-abort] :
    < while C do S , M > =>
    whileabortns((while C do S), M, T, M')
        if
            B[C] M = true
            /\ < S , M > => T
            /\ M' := finalState(T)
            /\ M' = Bottom .

  crl [while-ff] :
    < while C do S , M > =>
    whileffns((while C do S), M, M)
        if B[C] M = false .

  crl [repeat-ff] :
    < repeat S until C , M > =>
    repeatffns((repeat S until C), M, T, T', M'')
    if
      < S , M > => T
      /\ M' := finalState(T)
      /\ M' =/= Bottom
      /\ B[C] M' = false
      /\ < repeat S until C , M' > => T'
      /\ M'' := finalState(T') .

  crl [repeat-tt] :
    < repeat S until C , M > =>
    repeatttns((repeat S until C), M, T, M')
    if
      < S , M > => T
      /\ M' := finalState(T)
      /\ M' =/= Bottom
      /\ B[C] M' = true .

  crl [repeat-abort] :
    < repeat S until C , M > =>
    repeatabortns((repeat S until C), M, T, M')
    if
      < S , M > => T
      /\ M' := finalState(T)
      /\ M' = Bottom .

  crl [for-tt] :
    < for Q := E to E' do S , M > =>
    forttns((for Q := E to E' do S), M, T, T', T'', M''')
    if
      B[E <=? E'] M = true
      /\ < Q := E , M > => T
      /\ M' := finalState(T)
      /\ M' =/= Bottom
      /\ < S , M' > => T'
      /\ M'' := finalState(T')
      /\ M'' =/= Bottom
      /\ < for Q := Q ++ 1 to E' do S , M'' > => T''
      /\ M''' := finalState(T'') .

  crl [for-ff] :
    < for Q := E to E' do S , M > =>
    forffns((for Q := E to E' do S), M, M)
    if
      B[E <=? E'] M = false .

  crl [for-abort] :
    < for Q := E to E' do S , M > =>
    forabortns((for Q := E to E' do S), M, T, T', M'')
    if
      B[E <=? E'] M = true
      /\ < Q := E , M > => T
      /\ M' := finalState(T)
      /\ < S , M' > => T'
      /\ M'' := finalState(T')
      /\ M'' = Bottom .

  rl [abort] :
    < abort , M > => abortns(abort, M, Bottom) .

  crl [assert-tt] :
    < assert C before S , M > =>
    assertttns(assert C before S, M, T, M')
    if
        B[C] M = true
        /\ < S , M > => T
        /\ M' := finalState(T) .

  crl [assert-ff] :
    < assert C before S , M > =>
    assertffns(assert C before S, M, Bottom)
    if B[C] M = false .

  crl [or1] : 
    < S or S' , M > =>
    or1ns(S or S', M, T, M')
    if 
      < S , M > => T 
      /\ M' := finalState(T) .

  crl [or2] : 
    < S or S' , M > =>
    or2ns(S or S', M, T, M')
    if 
      < S' , M > => T 
      /\ M' := finalState(T) .

  crl [block] : 
    < begin D S end , M > => 
    blockns(begin D S end, M, T, T', M'' [DV(D) |-> M])
    if 
      < D , M > => T 
      /\ M' := finalState(T)
      /\ < S , M' > => T'
      /\ M'' := finalState(T')
      /\ M'' =/= Bottom .
      
  crl [block] : 
    < begin D S end , M > => 
    blockns(begin D S end, M, T, T', Bottom)
    if 
      < D , M > => T 
      /\ M' := finalState(T)
      /\ < S , M' > => T'
      /\ finalState(T') = Bottom .

  crl [var] :
    < var Q := E ; D , M > => 
    varns(var Q := E ; D, M, T, M')
    if 
      < D , M [Q |-> A[E] M] > => T 
      /\ M' := finalState(T) .

  rl [none] :
    < emptyDecv , M > => nonens(emptyDecv, M, M) .


endm
