mod SOS-WHILE-PROOFS is

  pr STATE .
  pr WHILE-SYNTAX .
  pr A-SYNTAX .
  pr A-SEMANTICS .
  pr B-SYNTAX .
  pr B-SEMANTICS .

  sort Tree Config Result Bottom .
  subsort Config Tree < Result .

  op <_,_> : Stat State -> Config .
  op Bottom : -> State [ctor] .

  op skipsos : Stat State State -> Tree .
  op asssos : Stat State State -> Tree .
  op comp1sos : Stat State Tree Stat State -> Tree .
  op comp2sos : Stat State Tree Stat State -> Tree .
  op ifttsos : Stat State Stat State -> Tree .
  op ifffsos : Stat State Stat State -> Tree .
  op whilesos : Stat State Stat State -> Tree .
  op repeatsos : Stat State Stat State -> Tree .
  op forsos : Stat State Stat State -> Tree .
  op abortsos : Stat State State -> Tree .
  op compabortsos : Stat State Tree State -> Tree .
  op assertsos : Stat State Stat State -> Tree .
  op or1sos : Stat State Stat State -> Tree .
  op or2sos : Stat State Stat State -> Tree .
  op par1sos : Stat State Tree Stat State -> Tree .
  op par2sos : Stat State Tree Stat State -> Tree .
  op par3sos : Stat State Tree Stat State -> Tree .
  op par4sos : Stat State Tree Stat State -> Tree .
  op protectsos : Stat State Tree State -> Tree .


  op finalState : Tree -> State .
  op finalStat : Tree -> Stat .
  op isTerminal : Tree -> Bool .

  vars M M' M'' : State .
  vars Q : Qid .
  vars E E' : Exp .
  vars S S' S1 S1' S2 S2' : Stat .
  vars T T' : Tree .
  vars C : Cond .

  eq isTerminal(asssos(S, M, M')) = true .
  eq isTerminal(skipsos(S, M, M')) = true .
  eq isTerminal(abortsos(S, M, M')) = true .
  eq isTerminal(compabortsos(S, M, T, M')) = true .
  eq isTerminal(protectsos(S, M, T, M')) = true .
  eq isTerminal(seqsos(T, T')) = isTerminal(T') .
  eq isTerminal(T) = false [owise] .

  eq finalStat(comp1sos(S, M, T, S', M')) = S' .
  eq finalStat(comp2sos(S, M, T, S', M')) = S' .
  eq finalStat(ifttsos(S, M, S', M')) = S' .
  eq finalStat(ifffsos(S, M, S', M')) = S' .
  eq finalStat(whilesos(S, M, S', M')) = S' .
  eq finalStat(repeatsos(S, M, S', M')) = S' .
  eq finalStat(forsos(S, M, S', M')) = S' .
  eq finalStat(assertsos(S, M, S', M')) = S' .
  eq finalStat(or1sos(S, M, S', M')) = S' .
  eq finalStat(or2sos(S, M, S', M')) = S' .
  eq finalStat(par1sos(S, M, T, S', M')) = S' .
  eq finalStat(par2sos(S, M, T, S', M')) = S' .
  eq finalStat(par3sos(S, M, T, S', M')) = S' .
  eq finalStat(par4sos(S, M, T, S', M')) = S' .


  eq finalState(asssos(S, M, M')) = M' .
  eq finalState(skipsos(S, M, M')) = M' .
  eq finalState(comp1sos(S, M, T, S', M')) = M' .
  eq finalState(comp2sos(S, M, T, S', M')) = M' .
  eq finalState(ifttsos(S, M, S', M')) = M' .
  eq finalState(ifffsos(S, M, S', M')) = M' .
  eq finalState(whilesos(S, M, S', M')) = M' .
  eq finalState(repeatsos(S, M, S', M')) = M' .
  eq finalState(forsos(S, M, S', M')) = M' .
  eq finalState(abortsos(S, M, M')) = M' .
  eq finalState(compabortsos(S, M, T, M')) = M' .
  eq finalState(assertsos(S, M, S', M')) = M' .
  eq finalState(or1sos(S, M, S', M')) = M' .
  eq finalState(or2sos(S, M, S', M')) = M' .
  eq finalState(par1sos(S, M, T, S', M')) = M' .
  eq finalState(par2sos(S, M, T, S', M')) = M' .
  eq finalState(par3sos(S, M, T, S', M')) = M' .
  eq finalState(par4sos(S, M, T, S', M')) = M' .
  eq finalState(protectsos(S, M, T, M')) = M' .


  op isAbort : Tree -> Bool .
  eq isAbort(abortsos(S, M, M')) = true .
  eq isAbort(compabortsos(S, M, T, M')) = true .
  eq isAbort(T) = false [owise] .

  rl [assign] :
    < Q := E , M > => asssos(Q := E, M, M [Q |-> A[E] M]) .

  rl [skip] :
    < skip , M > => skipsos(skip, M, M) .

  crl [comp1] :
    < (S1 ; S2) , M > => comp1sos((S1 ; S2), M, T, (S1' ; S2), M')
    if
        < S1 , M > => T
        /\ isTerminal(T) = false
        /\ isAbort(T) = false
        /\ M' := finalState(T)
        /\ S1' := finalStat(T) .

  crl [comp2] :
    < (S1 ; S2) , M > => comp2sos((S1 ; S2), M, T, S2, M')
    if
        < S1 , M > => T
        /\ isTerminal(T) = true
        /\ isAbort(T) = false
        /\ M' := finalState(T) .

  crl [comp-abort] :
    < (S1 ; S2) , M > => compabortsos((S1 ; S2), M, T, Bottom)
    if
        < S1 , M > => T
        /\ isAbort(T) = true .

  crl [iftt] :
    < if C then S1 else S2 , M > =>
    ifttsos(if C then S1 else S2, M, S1, M)
    if B[C] M = true .

  crl [ifff] :
    < if C then S1 else S2 , M > =>
    ifffsos(if C then S1 else S2, M, S2, M)
    if B[C] M = false .

  rl [while] :
    < while C do S , M > =>
    whilesos(while C do S, M,
      if C then (S ; while C do S) else skip, M) .

  rl [repeat] :
    < repeat S until C , M > =>
    repeatsos((repeat S until C), M,
      (S ; if C then skip else (repeat S until C)), M) .

  rl [for] :
    < for Q := E to E' do S , M > =>
      forsos((for Q := E to E' do S), M, if E <=? E' then
      (Q := E ; S ; (for Q := Q ++ 1 to E' do S)) else skip, M) .

  rl [abort] :
    < abort , M > => abortsos(abort, M, Bottom) .

  rl [assert] :
    < assert C before S , M > =>
    assertsos(assert C before S, M,
    if C then S else abort , M) .

  rl [or1] : 
    < S or S' , M > => or1sos(S or S', M, S, M) .

  rl [or2] : 
    < S or S' , M > => or2sos(S or S', M, S', M) .

  crl [par1] : 
    < S1 par S2 , M > => 
    par1sos(S1 par S2, M, T, S1' par S2, M')
    if 
      < S1 , M > => T 
      /\ isTerminal(T) = false
      /\ M' := finalState(T)
      /\ S1' := finalStat(T) .

  crl [par2] :
    < S1 par S2 , M > => 
    par2sos(S1 par S2, M, T, S2, M')
    if 
      < S1 , M > => T 
      /\ M' := finalState(T) 
      /\ isTerminal(T) = true .

  crl [par3] : 
    < S1 par S2 , M > => 
    par3sos(S1 par S2, M, T, S1 par S2', M')
    if 
      < S2 , M > => T 
      /\ isTerminal(T) = false
      /\ M' := finalState(T)
      /\ S2' := finalStat(T) .

  crl [par4] :
    < S1 par S2 , M > => 
    par4sos(S1 par S2, M, T, S1, M')
    if 
      < S2 , M > => T 
      /\ M' := finalState(T) 
      /\ isTerminal(T) = true .

  crl [protect] : 
    < protect S , M > => 
    protectsos(protect S, M, T, M')
    if 
      run(< S , M >) => T 
      /\ isTerminal(T) = true
      /\ M' := finalState(T) .



  *** CIERRE TRANSITIVO

  op seqsos : Tree Tree -> Tree [assoc] .
  op run : Config -> Tree .

  eq finalState(seqsos(T, T')) = finalState(T') .

  crl [run-step] :
    run(< S1 , M >) => seqsos(T, run(< S1' , M' >))
    if
      < S1 , M > => T
      /\ isTerminal(T) = false
      /\ S1' := finalStat(T)
      /\ M' := finalState(T) .

  crl [run-end] :
    run(< S1 , M >) => T
    if
      M =/= Bottom
      /\ < S1 , M > => T
      /\ isTerminal(T) = true .

endm
