fmod WHILE-SYNTAX is

  pr QID .
  pr A-SYNTAX .
  pr B-SYNTAX .

  sort Stat Assign .
  subsort Assign < Stat .

  op abort : -> Stat [ctor] .
  op skip : -> Stat [ctor] .
  op _:=_ : Qid Exp -> Assign .
  op _;_ : Stat Stat -> Stat [prec 100 assoc] .
  op if_then_else_ : Cond Stat Stat -> Stat .
  op while_do_ : Cond Stat -> Stat .
  op repeat_until_ : Stat Cond -> Stat .
  op for_to_do_ : Assign Exp Stat -> Stat .
  op assert_before_ : Cond Stat -> Stat .
  op _or_ : Stat Stat -> Stat .
  op _par_ : Stat Stat -> Stat .
  op protect_ : Stat -> Stat .

endfm
