fmod SEMANTIC-STATIC is
  
  pr EXP-SEMANTICS .
  pr TYPE-ENV .
  pr TYPED-WHILE-SYNTAX .

  op _|-_ : TypeEnv Exp -> Type .
  op _|-_ : TypeEnv Stat -> StatType .

  vars TE : TypeEnv .
  vars T : Type .
  vars BT : BasicType .
  vars I : Int .
  vars Q : Qid .
  vars E E' : Exp .
  vars S S' : Stat .

  eq TE |- I = int .
  eq TE |- true = bool .
  eq TE |- false = bool .
  eq TE |- Q = TE(Q) .

  eq TE |- (E ++ E') =
    if TE |- E == int and TE |- E' == int 
    then int else error fi .


  eq TE |- abort = ok .
  eq TE |- skip = ok .

  eq TE |- (BT Q := E) = 
    if TE [Q |-> BT] =/= errorEnv and TE |- E == BT 
    then ok else ko fi .

  eq TE |- (Q := E) =
    if TE(Q) =/= error and 
    TE(Q) == TE |- E then ok else ko fi .

  eq TE |- (S ; S') = 
    if TE |- S == ok and TE |- S' == ok
    then ok else ko fi .

  eq TE |- (if E then S else S') = 
    if TE |- E == bool
    and TE |- S == ok
    and TE |- S' == ok 
    then ok else ko fi .

  eq TE |- (while E do S) = 
    if TE |- E == bool
    and TE |- S == ok
    then ok else ko fi .

  eq TE |- (repeat S until E) = 
    if TE |- S == ok
    and TE |- E == bool
    then ok else ko fi .

  eq TE |- (for (BT Q := E) to E' do S) = 
    if BT == int 
    and TE |- E == int
    and TE [Q |-> BT] =/= errorEnv
    and TE |- E' == int
    and TE [Q |-> BT] |- S == ok
    then ok else ko fi .

endfm
