fmod SEMANTIC-STATIC is
  
  pr EXP-SEMANTICS .
  pr TYPE-ENV .
  pr TYPED-WHILE-SYNTAX .

  op _|-_ : TypeEnv Exp -> Type .
  op _|-_ : TypeEnv Stat -> StatType .

  vars TE : TypeEnv .
  vars T : Type .
  vars I : Int .
  vars Q : Qid .
  vars E E' : Exp .

  eq TE |- I = int .
  eq TE |- true = bool .
  eq TE |- false = bool .
  eq TE |- Q = TE(Q) .

  eq TE |- (E ++ E') =
    if TE |- E == int and TE |- E' == int 
    then int else error fi .


  eq TE |- abort = ok .
  eq TE |- skip = ok .

  eq TE |- (T Q := E) = 
    if TE [Q |-> T] =/= errorEnv and TE |- E == T 
    then ok else statError fi .

endfm
