fmod TYPE-ENV is
  
  pr QID .

  sort Type BasicType TypeEnv StatType .
  subsort BasicType StatType < Type .

  op ok : -> StatType [ctor] .
  op statError : -> StatType [ctor] .

  ops int bool : -> BasicType [ctor] .
  op error : -> Type [ctor] .

  op emptyEnv : -> TypeEnv [ctor] .
  op errorEnv : -> TypeEnv [ctor] .
  op [_|->_] : Qid Type -> TypeEnv [ctor] .
  op __ : TypeEnv TypeEnv -> TypeEnv [ctor assoc comm id: emptyEnv] .
  op _(_) : TypeEnv Qid -> Type .

  vars Q : Qid .
  vars TE : TypeEnv .
  vars T T' : Type .

  eq TE [Q |-> T] [Q |-> T'] = errorEnv . 
  ceq errorEnv TE = errorEnv if TE =/= emptyEnv .

  eq TE [Q |-> T] (Q) = T .
  eq TE (Q) = error [owise] .

endfm
