fmod B-SEMANTICS is

  pr BOOL .
  pr B-SYNTAX .
  pr A-SEMANTICS .
  pr STORE .
  pr ENVV .

  op B[_](_._) : Cond Store Envv -> Bool .

  vars S : Store .
  vars V : Envv .
  vars E E' : Exp .
  vars C C' : Cond .

  eq B[true] (S . V) = true .
  eq B[false] (S . V) = false .

  ceq B[E =? E'] (S . V) = true 
    if (A[E] (S . V)) == (A[E'] (S . V)) .

  eq B[E =? E'] (S . V) = false [owise] .

  ceq B[E <=? E'] (S . V) = true
    if (A[E] (S . V)) <= (A[E'] (S . V)) .

  eq B[E <=? E'] (S . V) = false [owise] .

  ceq B[! C] (S . V) = true 
    if B[C] (S . V) == false .

  eq B[! C] (S . V) = false [owise] .

  ceq B[C &&? C'] (S . V) = true
    if (B[C] (S . V) == true) and (B[C'] (S . V) == true) .

  eq B[C &&? C'] (S . V) = false [owise] .

endfm
