fmod STORE is

  pr NAT .
  pr INT .
  pr LOC .

  sort Store Mem Next .

  op emptyMem : -> Mem [ctor] .
  op [_:=_] : Loc Int -> Mem [ctor] .
  op __ : Mem Mem -> Mem [ctor assoc comm id: emptyMem] .
  op [next :=_] : Loc -> Next [ctor] .
  op __ : Mem Next -> Store [ctor] .
  op _[_|->_] : Store Loc Int -> Store .

  vars M : Mem .
  vars L : Loc .
  vars I I' : Int .
  vars N : Nat .
  vars NX : Next .

  *** Añadir o modificar memoria

  eq M [L := I] NX [L |-> I'] = M [L := I'] NX .
  eq M NX [L |-> I] = M [L := I] NX [owise] .


  *** Modificar next 
  op _[next |->_] : Store Loc -> Store . 
  eq M NX [next |-> L] = M [next := L] .
  
  *** Recuperar el valor de una dirección
  op __ : Store Loc ~> Int .
  eq M [L := I] NX L = I . 

endfm
