fmod WHILE-SYNTAX is

  pr A-SYNTAX .
  pr B-SYNTAX .
  pr STATE .

  sort Stat Assign .
  subsort Assign < Stat .

  op abort : -> Stat [ctor] .
  op skip : -> Stat [ctor] .
  op _:=_ : Qid Exp -> Assign [ctor] .
  op _;_ : Stat Stat -> Stat [ctor prec 100 assoc] .
  op if_then_else_ : Cond Stat Stat -> Stat [ctor] .
  op while_do_ : Cond Stat -> Stat [ctor] .
  op repeat_until_ : Stat Cond -> Stat [ctor] .
  op for_to_do_ : Assign Exp Stat -> Stat [ctor] .
  op assert_before_ : Cond Stat -> Stat [ctor] .
  op _or_ : Stat Stat -> Stat [ctor] .
  op _par_ : Stat Stat -> Stat [ctor] .
  op protect_ : Stat -> Stat [ctor] .

endfm
